"""Demo workspace inactivity reset.

When `amit@demo.team` (the public demo account) has been inactive for more than
`DEMO_INACTIVITY_THRESHOLD_SECONDS`, the next `/auth/demo-login` call wipes the
bulk of accumulated workspace data and reseeds a small curated sample — so
every fresh demo session starts on a clean, showcase-ready slate.

Guard rails:
    • Only runs against the workspace owned by `amit@demo.team`. Real users
      and real workspaces are NEVER touched.
    • The demo user, the 6 seeded teammates, and the workspace_billing row
      are PRESERVED — only generated content (chats, messages, tasks, calls,
      uploads, dev projects, etc.) is reset.
    • Idempotent: calling multiple times in a row is a no-op once the reseed
      has run (because the latest reseeded message timestamp is now "fresh").
"""
from __future__ import annotations

from datetime import datetime, timedelta, timezone
from typing import Optional

from deps import db, logger, new_id, now_iso

DEMO_USER_EMAIL = "amit@demo.team"
DEMO_INACTIVITY_THRESHOLD_SECONDS = 3600  # 1 hour

# Collections whose rows are scoped to a workspace_id and should be wiped on
# reset. Order matters slightly (children before parents) but Mongo's lack of
# foreign keys means we can safely batch in any order.
_WORKSPACE_SCOPED_COLLECTIONS = [
    # generated by users / agents
    "messages",            # scoped via chat_id below (special-cased)
    "chats",
    "folders",
    "tasks",
    "calls",
    "approvals",
    "ai_responses",
    "ai_threads",
    "ai_thread_versions",
    "saved_research",
    "files",
    "sms_messages",
    "phone_invites",
    "invites",
    "invite_links",
    "external_contacts",
    "user_chat_states",
    "improvement_proposals",
    "audit_logs",
    "memory_items",
    "memory_access_rules",
    "integrations",
    "payment_transactions",
    # ai employees
    "ai_employee_tasks",
    "ai_employee_activity",
    "ai_employee_subscriptions",
    "ai_employee_credit_ledger",
    "ai_credit_ledger",
    "ai_employee_waitlist",
    "meetings",
    "agent_policies",
    "chat_ai_usage",
    "chat_ai_settings",
    # dev os
    "dev_projects",
    "dev_audit_logs",
    "dev_builds",
    "dev_bug_reports",
    "dev_execution_feedback",
    "dev_github_connections",
    "dev_netlify_links",
    "dev_os_digests",
    "dev_preview_comments",
    "dev_preview_deployments",
    "dev_project_memory",
    "dev_pull_requests",
    "dev_release_notes",
    "dev_tasks",
    "dev_vercel_links",
    # bookkeeping
    "bk_pending_qb_sync",
    "bk_statements",
    "bk_transactions",
]


async def get_demo_user_and_workspace() -> tuple[Optional[dict], Optional[str]]:
    """Return (demo_user, demo_workspace_id) or (None, None) if unseeded."""
    user = await db.users.find_one({"email": DEMO_USER_EMAIL}, {"_id": 0})
    if not user:
        return None, None
    return user, user["workspace_id"]


async def _last_activity_at(workspace_id: str) -> Optional[datetime]:
    """Newest message timestamp across all chats in this workspace, treated as
    the "last activity" signal. Returns None if no messages exist yet."""
    chats = await db.chats.find(
        {"workspace_id": workspace_id}, {"_id": 0, "id": 1},
    ).to_list(5000)
    if not chats:
        return None
    chat_ids = [c["id"] for c in chats]
    latest = await db.messages.find_one(
        {"chat_id": {"$in": chat_ids}},
        sort=[("created_at", -1)],
        projection={"_id": 0, "created_at": 1},
    )
    if not latest:
        return None
    ts = latest["created_at"]
    if isinstance(ts, str):
        try:
            return datetime.fromisoformat(ts.replace("Z", "+00:00"))
        except ValueError:
            return None
    return ts


async def _wipe_workspace_data(workspace_id: str) -> dict:
    """Hard-delete every workspace-scoped row in the collections listed in
    _WORKSPACE_SCOPED_COLLECTIONS. Returns a dict of {collection: deleted_count}
    for observability. Users + workspaces + workspace_billing are NOT touched."""
    counts: dict[str, int] = {}

    # messages first, since they're keyed by chat_id not workspace_id.
    chats = await db.chats.find(
        {"workspace_id": workspace_id}, {"_id": 0, "id": 1},
    ).to_list(5000)
    chat_ids = [c["id"] for c in chats]
    if chat_ids:
        r = await db.messages.delete_many({"chat_id": {"$in": chat_ids}})
        counts["messages"] = r.deleted_count

    # Workspace-scoped collections (skip messages — already handled).
    for coll in _WORKSPACE_SCOPED_COLLECTIONS:
        if coll == "messages":
            continue
        try:
            r = await db[coll].delete_many({"workspace_id": workspace_id})
            if r.deleted_count:
                counts[coll] = r.deleted_count
        except Exception as e:
            logger.warning("[demo-reset] could not wipe %s: %s", coll, e)

    return counts


async def _reseed_sample(workspace_id: str, owner: dict, all_users: list[dict]) -> None:
    """Insert a small, curated sample after a wipe.

    Sample shape:
      • 3 group chats (Engineering / Q2 Launch / Marketing) — each with 3-4
        seed messages so the chat list isn't empty.
      • 1 personal AI chat per user.
      • 1 active task on the first group.
      • 1 Dev OS showcase project (via the existing franchise seeder).
    """
    if not all_users:
        return

    now = now_iso()
    now_dt = datetime.now(timezone.utc)

    # ── Project folder ───────────────────────────────────────────────
    folder = {
        "id": new_id(),
        "workspace_id": workspace_id,
        "name": "Q2 Product Launch",
        "description": "Pricing, launch markets, and go-to-market plan for the new Pro tier.",
        "owner_id": owner["id"],
        "member_ids": [u["id"] for u in all_users[:4]],
        "created_at": now,
    }
    await db.folders.insert_one(folder.copy())

    # ── 3 group chats ────────────────────────────────────────────────
    group_defs = [
        ("Engineering", "Backend, infra, and frontend chatter.", "engineering"),
        ("Q2 Product Launch", "Launch market + pricing decisions.", "product"),
        ("Marketing Site Refresh", "Site redesign + copy review.", "marketing"),
    ]
    group_chats = []
    for name, desc, category in group_defs:
        c = {
            "id": new_id(),
            "workspace_id": workspace_id,
            "type": "group",
            "kind": "group",
            "name": name,
            "description": desc,
            "category": category,
            "project_folder_id": folder["id"] if name == "Q2 Product Launch" else None,
            "default_models": ["chatgpt", "claude", "gemini"],
            "member_ids": [u["id"] for u in all_users],
            "admin_ids": [owner["id"]],
            "posting_policy": "all",
            "posting_user_ids": [],
            "bot_role_ids": [],
            "created_by": owner["id"],
            "created_at": now,
            "pinned_message_ids": [],
        }
        await db.chats.insert_one(c.copy())
        group_chats.append(c)

    # ── Sample messages ──────────────────────────────────────────────
    seed_msgs = [
        (group_chats[0]["id"], owner["id"],
         "Morning team — let's plan this week. What are the top eng priorities?"),
        (group_chats[0]["id"], all_users[1]["id"] if len(all_users) > 1 else owner["id"],
         "Finishing the dashboard latency fix today, then I can pair on the search rework tomorrow."),
        (group_chats[0]["id"], all_users[2]["id"] if len(all_users) > 2 else owner["id"],
         "Try `@dev` here btw — I want to ask the AI architect about the search index design."),
        (group_chats[1]["id"], owner["id"],
         "Welcome team. Let's lock the Pro-tier launch market and pricing this week."),
        (group_chats[2]["id"], owner["id"],
         "New hero copy proposal is in the doc — would love eyes by EOD."),
    ]
    msg_rows = []
    for offset, (chat_id, sender_id, body) in enumerate(seed_msgs):
        msg_rows.append({
            "id": new_id(),
            "chat_id": chat_id,
            "sender_id": sender_id,
            "message_type": "text",
            "body": body,
            "parent_message_id": None,
            "metadata": {"source": "demo_reset"},
            "reactions": {},
            "created_at": (now_dt - timedelta(minutes=15 - offset * 3)).isoformat(),
            "edited_at": None,
            "deleted_at": None,
        })
    await db.messages.insert_many([m.copy() for m in msg_rows])

    # ── Personal AI chat per user ────────────────────────────────────
    personal_chats = []
    for u in all_users:
        personal_chats.append({
            "id": new_id(),
            "workspace_id": workspace_id,
            "type": "personal_ai",
            "kind": "personal_ai",
            "name": "My AI Assistant",
            "description": "Your personal AI workspace.",
            "default_models": ["claude"],
            "member_ids": [u["id"]],
            "admin_ids": [u["id"]],
            "posting_policy": "all",
            "posting_user_ids": [],
            "bot_role_ids": [],
            "created_by": u["id"],
            "created_at": now,
            "pinned_message_ids": [],
        })
    if personal_chats:
        await db.chats.insert_many([c.copy() for c in personal_chats])

    # ── 1 sample task ────────────────────────────────────────────────
    assignee = all_users[2] if len(all_users) > 2 else owner
    await db.tasks.insert_one({
        "id": new_id(),
        "workspace_id": workspace_id,
        "project_folder_id": folder["id"],
        "source_chat_id": group_chats[1]["id"],
        "source_message_id": None,
        "title": "Finalise pricing for Pro tier launch",
        "description": "Compare $20 / $25 / $29 ladders and finalise the one we lead with.",
        "assigned_to": assignee["id"],
        "created_by": owner["id"],
        "due_date": (now_dt + timedelta(days=2)).isoformat(),
        "priority": "high",
        "status": "todo",
        "created_at": now,
        "completed_at": None,
    })

    # ── AI Employee showcase: an active "Priya AI" (CMO) with a week of work ──
    try:
        from ai_employees_catalog import get_employee
        emp = get_employee("cmo")
        if emp:
            await db.ai_employee_subscriptions.insert_one({
                "id": new_id(), "workspace_id": workspace_id, "employee_key": "cmo",
                "started_by": owner["id"], "display_first_name": "Priya", "display_full_name": "Priya AI",
                "phase": "trial", "status": "trial_active",
                "trial_started_at": now, "trial_ends_at": (datetime.now(timezone.utc) + timedelta(days=7)).isoformat(),
                "trial_credits_total": emp.get("trial_credits", 0), "trial_credits_used": 0,
                "monthly_credits_total": emp.get("monthly_credits", 0), "monthly_credits_used": 0,
                "monthly_price": emp.get("monthly_price", 0), "auto_convert": True,
                "credit_limit_override": None, "per_task_credit_limit": None,
                "approval_threshold_credits": 50, "stripe_subscription_id": None,
                "created_at": now, "updated_at": now,
            })
            hrs = emp.get("hours_saved_per_task", 0.5)
            for i, q in enumerate([
                "Draft the Q3 launch announcement for LinkedIn",
                "Write 5 subject lines for the weekly newsletter",
                "Summarize this week's marketing metrics",
            ]):
                await db.ai_employee_tasks.insert_one({
                    "id": new_id(), "workspace_id": workspace_id, "employee_key": "cmo",
                    "display_full_name": "Priya AI", "question": q, "answer_preview": "Done.",
                    "credits_used": 2, "estimated_hours_saved": hrs,
                    "completed_at": (datetime.now(timezone.utc) - timedelta(days=i)).isoformat(),
                    "completed_by_user": owner["id"],
                })
    except Exception as e:
        logger.warning("[demo-reset] ai employee sample seed failed: %s", e)

    # ── An upcoming meeting so 'Prepare me' has a real call to brief ──
    try:
        first_group = await db.chats.find_one(
            {"workspace_id": workspace_id, "type": {"$ne": "personal_ai"}}, {"_id": 0, "id": 1},
        )
        await db.meetings.insert_one({
            "id": new_id(), "workspace_id": workspace_id,
            "chat_id": first_group["id"] if first_group else None,
            "title": "Weekly Team Sync",
            "start_at": (datetime.now(timezone.utc) + timedelta(days=1)).isoformat(),
            "attendees": ["Amit", "Priya", "Raj"], "notes": "Review roadmap, blockers, and this week's numbers.",
            "created_by": owner["id"], "created_at": now,
        })
    except Exception as e:
        logger.warning("[demo-reset] meeting sample seed failed: %s", e)

    # ── Dev OS showcase (idempotent on its own) ──────────────────────
    try:
        from services.dev_os_sample_seed import seed_franchise_sample
        await seed_franchise_sample(workspace_id, owner["id"])
    except Exception as e:
        logger.warning("[demo-reset] dev_os sample seed failed: %s", e)


async def reset_demo_workspace(workspace_id: str) -> dict:
    """Wipe workspace-scoped data then reseed a curated sample.

    Returns a `{deleted: {coll: n, ...}}` dict for observability/logging.
    """
    owner = await db.users.find_one(
        {"workspace_id": workspace_id, "role": "owner"}, {"_id": 0},
    )
    users = await db.users.find(
        {"workspace_id": workspace_id, "status": {"$ne": "removed"}}, {"_id": 0},
    ).to_list(50)
    if not owner or not users:
        logger.warning("[demo-reset] no owner/users for workspace=%s — skipping", workspace_id)
        return {"deleted": {}, "skipped": True}

    deleted = await _wipe_workspace_data(workspace_id)
    await _reseed_sample(workspace_id, owner, users)
    logger.info("[demo-reset] reset workspace=%s deleted=%s", workspace_id, deleted)
    return {"deleted": deleted, "skipped": False}


async def maybe_run_inactivity_cleanup() -> dict:
    """Top-level: if the demo workspace has been idle for ≥1 hour, reset it.

    Always safe to call from /auth/demo-login — no-ops when:
      • The demo user isn't seeded.
      • Activity within the last hour exists (someone is still using the demo).
    """
    user, ws_id = await get_demo_user_and_workspace()
    if not user or not ws_id:
        return {"ran": False, "reason": "no_demo_user"}
    last = await _last_activity_at(ws_id)
    if last is None:
        # No messages at all — empty workspace. Seed sample so the first
        # demo-login still lands on a populated UI.
        result = await reset_demo_workspace(ws_id)
        return {"ran": True, "reason": "empty_workspace", **result}
    age = (datetime.now(timezone.utc) - last).total_seconds()
    if age < DEMO_INACTIVITY_THRESHOLD_SECONDS:
        return {
            "ran": False,
            "reason": "still_active",
            "last_active_seconds_ago": int(age),
        }
    result = await reset_demo_workspace(ws_id)
    return {
        "ran": True,
        "reason": "inactive",
        "last_active_seconds_ago": int(age),
        **result,
    }
